### ISSUE TITLE
outdated benchmark results

### ISSUE THREAD

**Issue by kwiatkk1** [allegro/node-worker-nodes#12]
Seems that with latest versions of node.js (7.5.0+) this library is not outperforming its competitors as it is previously stated in a benchmark results.

**Comment by kwiatkk1** [comment]
Also add the test cases from the example attached to https://github.com/allegro/node-worker-nodes/issues/18.

**Comment by rafixer** [comment]
updated on: https://github.com/allegro/node-worker-nodes/commit/29232a2b3a809867121eddd828a3fe35f7ea9db3
