### ISSUE TITLE
NodeJS 8.1.0 using NVM SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by antoine-pous** [allegro/node-worker-nodes#14]
Hi!

I'm currently facing an issue when i use strict with your library.

```console
/node_modules/worker-nodes/lib/pool.js:3
const { TimeoutError, ProcessTerminatedError, MaxConcurrentCallsError } = require('./errors');
```

**Comment by kwiatkk1** [comment]
Hi Antoine!

Are you sure, that the node@8 is used? I think that `SyntaxError: Unexpected token {` is not related to any strict mode, but its rather a result of using node of version below 6.5.x (see node's support for destructuring: http://node.green/#ES2015-syntax-destructuring--declarations).

To test if strict mode breaks something, I have run the code on node@8.1.3 with `--use_strict` flag and everything seems to be OK.

**Comment by antoine-pous** [comment]
Hi!

After some tests i found a solution. In fact you're right, nvm set the wrong node version as default.

After update the default version I have written a small function to avoid a conflict with the node cache.

https://gist.github.com/antoine-pous/a08710cc7fc63d98b130ed4f992e96ae

And all is ok now, maybe that can help someone else ;)
