### ISSUE TITLE
Feature request: add the ability to run "init" code at worker startup

### ISSUE THREAD

**Issue by csilvers** [allegro/node-worker-nodes#15]
We have the need to initialize some global data structures on our workers before they can start doing work.  In addition, the initialization depends on some runtime data known by the parent process.

We'd like to do something like this:
```
const workerNodes = require("worker-nodes");
const cacheSize = 100;
const workers = new workerNodes(myfile, options, () => initCache(cacheSize));
```
though that particular implementation probably wouldn't work.

Is such a thing possible?  It seems like it should be, by calling `handleCall` on worker startup, in addition to calling it every time we are starting a new task.  But I'm afraid I'm not up to the task of figuring out all the details.

**Comment by kwiatkk1** [comment]
Hi! Unfortunately there is no elegant solution for now to do this. 

I think that it would be an useful option to pass some data on start bas you suggested. But for now, as workers don't receive any custom options during initialization phase, we can take advantage of how workers loads (they simply report ready if the source is loaded), and make some workaround:

- in a master process, before spawning workers, create a config file:
```javascript
const WorkerNodes = require('worker-nodes');
const fs = require('fs');
const os = require('os');
const path = require('path');
const util = require('util');
const writeFileAsync = util.promisify(fs.writeFile);

async function run() {
    const tmpFilePath = path.join(os.tmpdir(), 'worker-startup-params.json');
    const workerInitOptions = {
        foo: 'bar',
        cacheSize: 100
    };

    // save worker config (hopefully using fast tmpfs access)
    await writeFileAsync(tmpFilePath, JSON.stringify(workerInitOptions));

    // start
    const workers = new WorkerNodes(require.resolve('./worker-source.js'), {
        autoStart: true,
        lazyStart: false,
        minWorkers: 4,
        maxWorkers: 4,
        maxTasksPerWorker: 1
    });

    // wait for all workers to be ready
    await workers.ready();
}

run().then(() => console.log('ready'));

```

- in a worker's code (worker-source.js) read the config:
```javascript
const os = require('os');
const path = require('path');

const workerCustomOptions = require(path.join(os.tmpdir(), 'worker-startup-params.json'));

console.log(`worker ${process.pid} up! custom options: ${JSON.stringify(workerCustomOptions)}`);
```

This should produce output similar to the following:
```shell
> node index.js
worker 57621 up! custom options: {"foo":"bar","cacheSize":100}
worker 57622 up! custom options: {"foo":"bar","cacheSize":100}
worker 57624 up! custom options: {"foo":"bar","cacheSize":100}
worker 57623 up! custom options: {"foo":"bar","cacheSize":100}
ready
```

I hope it helps in your use case.

But if passing a config via tmp file is not an acceptable solution, please wait for a final one (a new option like `initData`):

```javascript
const workers = new WorkerNodes(require.resolve('./worker-source.js'), {
    [...]
    initData: {
        cacheSize: 100
    }
});
```

**Comment by csilvers** [comment]
Thanks for the thoughtful reply!  I ended up making a temporary file, just like you did, but I did it for the entire entrypoint, not just for the config reading, which ended up being simpler.  My code is like this:
```
    const template = `${__dirname}/render_cache_${cacheSize}_XXXXXX.js`;
    const tmpobj = tmp.fileSync({template: template, discardDescriptor: true});
    const filename = tmpobj.name;
    const contents = `
const cache = require("./cache.js");
cache.init(${cacheSize});
module.exports = require("./render.js");
`;
    fs.writeFileSync(filename, contents);

    return new workerNodes(filename, options);
```

**Comment by kwiatkk1** [comment]
I think that I came up with the slightly better idea of solving this issue:
- we can take an advantage of that environment variables set in a master process are visible to its child processes (see: https://nodejs.org/api/process.html#process_process_env)
- so instead of hitting the filesystem and creating tmp files, we can simply use env to pass config data

So the code should look like this:

- in a master process, before spawning workers, create an env variable:
```javascript
const WorkerNodes = require('worker-nodes');

async function run() {

    // setup env variable
    process.env.WORKER_OPTIONS = JSON.stringify({
        spam: 'eggs',
        ham: 'cheese',
        cacheSize: 100
    });

    // start processes...
    const workers = new WorkerNodes(require.resolve('./worker-source.js'), {
        autoStart: true,
        lazyStart: false,
        minWorkers: 4,
        maxWorkers: 4,
        maxTasksPerWorker: 1
    });

    // ...and wait for all the workers to be ready before proceeding
    await workers.ready();
}

run().then(() => console.log('ready'));

```

- in a worker's code (worker-source.js) read the env variable:
```javascript
// receive config
const workerCustomOptions = JSON.parse(process.env.WORKER_OPTIONS);

console.log(`worker ${process.pid} up! custom options: ${JSON.stringify(workerCustomOptions)}`);
```

**Comment by csilvers** [comment]
Doh! -- a great approach. This is, like, what the environment is for...

**Comment by spencermountain** [comment]
thanks craig and Krzysztof, if anyone is still reading this, I was able to pass a function into the worker using [jsonfn](https://www.npmjs.com/package/jsonfn).
