### ISSUE TITLE
Transferring large JS objects can be slow

### ISSUE THREAD

**Issue by jeresig** [allegro/node-worker-nodes#18]
Thank you so much for your great library! I've been hitting an issue when trying to transfer large JS objects - they seem to be especially slow to encode/decode. I've put together a simple test case to analyze:

https://gist.github.com/jeresig/af003831559a99af63133189e088b4e6

It seems like passing through any JS object ends up being slow - however if we use our own `JSON.stringify`/`JSON.parse` and pass through just a string then it ends up being much faster.

We may just encode everything as a big string (non-JS object) and just parse that result, to get optimal speed. Any suggestions you have for improving the performance would be appreciated!

**Comment by kwiatkk1** [comment]
Hi John!

Thanks for the kind words about the library (and sorry for the delay in my response).

My thoughts about the issue:
- Unfortunately, JSON.stringify must be somewhere there, as we can only transfer primitive objects between processes (alternative: use something like https://github.com/audreyt/node-webworker-threads, but this means that we have only v8 in workers, not a full node runtime, so you must pack everything with something like browserify/webpack before, etc.)
- It appears that this is related to the relatively recent change (switch from BSON serializer to message-pack) -- I will dig into that and provide more info soon (message-pack gives us flexibility, but apparently, it negatively affects performance :/)
- In a meantime you can safely use lower version of library (1.3.1), the overhead there is not as dramatic as in the recent version (see: https://gist.github.com/kwiatkk1/a53db48c243d00918d2de2d39e71b1be#file-output-txt)

**Comment by kwiatkk1** [comment]
cc @csilvers

**Comment by noam-almog** [comment]
@kwiatkk1 I've also experienced issues with the streaming option.
the streaming was done in order for us not to have a limited buffer when sending messages, streaming does not define a buffer therefore we are not limited (which is very good)
the performance impact is significant but i think there must be a better way to solve this (and i did not have the time to do that so far, busy with alot of projects at the moment).
So to answer the question you sent me:
1. we can roll this change back (1.4.0) and dump the stream thing, but we will still have the buffer issue which have severe issues when you overflow it (node shuts down the process without any notification and basically brings the server down)
2. try to investigate how we can make the current implementation perform - or at least understand why it's underperform at the moment.

I don't really understand why this is not working. if we are using the blocking version:
send message -> marshal -> send payload -> receive it -> unmarshal -> execute and then respond in the same way.
stream scenario does exactly the same thing, send messages is basically causing a blocks the thread same way it does when not streaming (after all it's node, single process, marshal/unmarshal is very cpu bound).
can anyone offer some advice ?

**Comment by noam-almog** [comment]
I suspect this code: https://github.com/allegro/node-worker-nodes/blob/master/lib/worker/transport.js#L17
I think we should create a single stream on both ways and have a way which we reuse them to send multiple messages at the same time
