### ISSUE TITLE
how to use import,export in workerModule ?

### ISSUE THREAD

**Issue by wuchuguang** [allegro/node-worker-nodes#25]
test.js 
```
import workerNodes from 'worker-nodes';
const test1 = new workerNodes(path.resolve(__dirname, "test-model"));

```

test-model.js
```
import lib from './lib.js';   // **report cant use import,and export**
module.exports =async function(){
};
```

lib.js
```
export default {
  test(){
  }
}
```

**Comment by kwiatkk1** [comment]
Hi @wuchuguang! As node.js don't support es6 modules (i.e. import/export statements) out of the box, you can either transpile your code using babel or use feature flag that enables experimental native support (see: http://2ality.com/2017/09/native-esm-node.html).
