### ISSUE TITLE
Has this package been tested on typescript?

### ISSUE THREAD

**Issue by khan990** [allegro/node-worker-nodes#35]
Hi,

Its been few days that I am struggling to use this package on typescript.
Here is an online test implementation: https://repl.it/@JasimKhan/worker-nodes-test

Locally, I am trying to debug it using `ts-node`, but i dont get any break point in the worker tasks... Nor do I see console traces of their execution.

Can some one point me to some typescript usage of this package?

Thanks in advance.

**Comment by kwiatkk1** [comment]
Hi,

When using a debugger, keep in mind that workers have a separate execution contexts.
So look at the process/thread you're attached to while debugging.
I think that this is the problem, not that the package has any typescript compatibility issues.
