### ISSUE TITLE
Fix memory leak in WorkerProcess

### ISSUE THREAD

**Issue by Galcarmi** [allegro/node-worker-nodes#69]
Hey,

We’re using this lib in our service to run worker processes which bundles code with webpack.
following @yurynix  [PR](https://github.com/allegro/node-worker-nodes/pull/64) everything seemed to work fine.

We use this configuration for the pool
```
const POOL_OPTIONS = {
  minWorkers: 4,
  maxWorkers: 6,
  // Not passed in production, only used for testing.
  autoStart: process.env.POOL_TESTS_AUTO_START !== "false",
  // Not passed in production, only used for testing.
  taskTimeout: process.env.POOL_TESTS_TASK_TIMEOUT ?? seconds(55),
  workerType: "process",
  workerEndurance: 1,
};
```

After a while, we noticed that our node processes were leaking memory.
It took some time for us to understand that when a process is being killed after it finishes 1 job `(workerEndurance: 1 configuration)` we don’t close the server connection [here](https://github.com/allegro/node-worker-nodes/blob/adb07c1f8ee25255a6d8aedb16014a0b40232043/lib/worker/process.js#L117). This is causing server socket files to accumulate in os.tmpdir() [since the server never closes](https://github.com/allegro/node-worker-nodes/blob/adb07c1f8ee25255a6d8aedb16014a0b40232043/lib/worker/process.js#L41)

[I created a fork](https://github.com/Galcarmi/node-worker-nodes/pull/4/files) which fixes the issue (close server connection when child process exists)
I already tested it in production and it works great.

I'll create a PR to fix it in this package so I can continue use it in production.

**Comment by bgalek** [comment]
hi @Galcarmi, thx for issue and PR!
