### ISSUE TITLE
minWorkers/maxWorkers ambiguity

### ISSUE THREAD

**Issue by kwiatkk1** [allegro/node-worker-nodes#8]
The `minWorkers` option is only respected when initially reporting pool readiness, but should also be treated as a number of workers that the pool needs to keep running all the time, i.e.:
- on any accidental worker termination, pool should boot a new worker immediately (if `minWorkers` number is greater than the current number of healthy workers)
- a planned worker exit (for example as a result of `WorkerEndurance` value exceedance) should result in a spawn of a new worker before starting the process of termination the exhausted one (maybe even at cost of some extra calls above declared endurance).

**Comment by yurynix** [comment]
I think that somewhat handled in #62
